#ifndef _REG_H_
#define _REG_H_

#define MMIO_BASE		0x3F000000

#define GPIO_BASE		(MMIO_BASE + 0x200000)
#define GPFSEL0         (GPIO_BASE + 0x00)
#define GPFSEL1         (GPIO_BASE + 0x04)
#define GPFSEL2         (GPIO_BASE + 0x08)
#define GPFSEL3         (GPIO_BASE + 0x0C)
#define GPFSEL4         (GPIO_BASE + 0x10)
#define GPFSEL5         (GPIO_BASE + 0x14)
#define GPSET0          (GPIO_BASE + 0x1C)
#define GPSET1          (GPIO_BASE + 0x20)
#define GPCLR0          (GPIO_BASE + 0x28)
#define GPCLR1          (GPIO_BASE + 0x2C)
#define GPLEV0          (GPIO_BASE + 0x34)
#define GPLEV1          (GPIO_BASE + 0x38)
#define GPEDS0          (GPIO_BASE + 0x40)
#define GPEDS1          (GPIO_BASE + 0x44)
#define GPREN0          (GPIO_BASE + 0x4C)
#define GPREN1          (GPIO_BASE + 0x50)
#define GPFEN0          (GPIO_BASE + 0x58)
#define GPFEN1          (GPIO_BASE + 0x5C)
#define GPHEN0          (GPIO_BASE + 0x64)
#define GPHEN1          (GPIO_BASE + 0x68)
#define GPLEN0          (GPIO_BASE + 0x70)
#define GPLEN1          (GPIO_BASE + 0x74)
#define GPAREN0         (GPIO_BASE + 0x7C)
#define GPAREN1         (GPIO_BASE + 0x80)
#define GPAFEN0         (GPIO_BASE + 0x88)
#define GPAFEN1         (GPIO_BASE + 0x8C)   
#define GPPUD           (GPIO_BASE + 0x94)
#define GPPUDCLK0       (GPIO_BASE + 0x98)
#define GPPUDCLK1       (GPIO_BASE + 0x9C)
#define UART0_BASE      (MMIO_BASE + 0x201000)
#define UART0_DR        (UART0_BASE + 0x00)
#define UART0_RSRECR    (UART0_BASE + 0x04)
#define UART0_FR        (UART0_BASE + 0x18)
#define UART0_ILPR      (UART0_BASE + 0x20)
#define UART0_IBRD      (UART0_BASE + 0x24)
#define UART0_FBRD      (UART0_BASE + 0x28)
#define UART0_LCRH      (UART0_BASE + 0x2C)
#define UART0_CR        (UART0_BASE + 0x30)
#define UART0_IFLS      (UART0_BASE + 0x34)
#define UART0_IMSC      (UART0_BASE + 0x38)
#define UART0_RIS       (UART0_BASE + 0x3C)
#define UART0_MIS       (UART0_BASE + 0x40)
#define UART0_ICR       (UART0_BASE + 0x44)
#define UART0_DMACR     (UART0_BASE + 0x48)
#define UART0_ITCR      (UART0_BASE + 0x80)
#define UART0_ITIP      (UART0_BASE + 0x84)
#define UART0_ITOP      (UART0_BASE + 0x88)
#define UART0_TDR       (UART0_BASE + 0x8C)

#endif
